### ISSUE TITLE
Post-Build-Action not available - Zulip Notification

### ISSUE THREAD

**Issue by Philipp1909** [jenkinsci/zulip-plugin#16]
Hello,

unfortunately I can't select a stream or a topic under Post-Build-Actions as described in the documentation for Zulip-Jenkins Plugin. Does anyone have an idea where the problem might be?

Here i'm missing stream and topic
![post-build-aktionen](https://user-images.githubusercontent.com/42967341/53744356-2864e800-3e9d-11e9-856c-5c38a0ec2d87.JPG)

In the documentation you can choose a stream and topic.
![post-build-aktionen2 documentation](https://user-images.githubusercontent.com/42967341/53744417-4d595b00-3e9d-11e9-812d-f1266301db78.JPG)

Documentation: https://zulipchat.com/integrations/doc/jenkins

**Comment by timabbott** [comment]
@butchyyyy any idea what's going on here?

**Comment by butchyyyy** [comment]
@Philipp1909 The possibility to configure stream and topic in post build action is a recent addition to the plugin. The new version containing this functionallity was released under a new plugin id. My guess would be you have the old version of the plugin installed.

Can you please go to **Administration** -> **Plugin Manager** -> **Installed** tab and see what version of the plugin do you have? You should see something like this (note the version must be 1.0.0): 

![image](https://user-images.githubusercontent.com/17402486/53761797-ae495900-3ec6-11e9-8917-e395394ff877.png)

If you see a 0.1.x version, you'll have to install the new one. If you don't have 1.0.0 version avaiable, your plugin index is probably outdated. You can force an update by going to **Administration** -> **Plugin Manager** -> **Advanced** -> **Check now** button at the bottom right of the page.

Once you update the plugin index, 1.0.0 version of the plugin should be available. You can install the new version directly or as dependency by updaing the previous plugin to it's last release 0.1.4.

P.S.: If it turns out you already have the 1.0.0 version installed, i'll investigate further.

**Comment by Philipp1909** [comment]
Hello @butchyyyy ,
thank you for your quick answer. Now I installed the Zulip Plugin 1.0.0 and removed the old version. Now I can also specify the stream and topic in my jenkins job.
Unfortunately there is another error now, the Zulip URL from our server is changed automatically to "http://repo1.maven.org/maven2" after saving. 

my configuration
![zulip notification settings](https://user-images.githubusercontent.com/42967341/53791932-da96c100-3f2a-11e9-8661-87541136cc6c.JPG)

after saving
![zulip notification settings after saving](https://user-images.githubusercontent.com/42967341/53791949-e71b1980-3f2a-11e9-9682-153a07a8ae45.JPG)

**Comment by butchyyyy** [comment]
@Philipp1909 I can confirm the bug.
It's a configuration field name conflict which only occurs with certain other plugin(s) installed (i managed to reproduce the bug by installing the artifact resolver plugin).

I'll investigate and should have a fix published today.
Will keep you posted.

**Comment by butchyyyy** [comment]
I have released version 1.0.1 which adresses the issue. The new release should show up in the update center within 8 hours.

If the fix won't work for you or you run into any other issue, let me know!

**Comment by butchyyyy** [comment]
FYI: New version is now available in the update center.

**Comment by Philipp1909** [comment]
Hey @butchyyyy ,
Thanks for your support. I have now installed version 1.0.1, so I can set the URL correctly. However, it is no longer possible to disable the function "Enable Smart Notification". The function is always selected automatically. I have opened a new issue.
https://github.com/jenkinsci/zulip-plugin/issues/17
